<?php

declare(strict_types=1);

namespace App\Services\Hostfully\Models;

class Webhooks
{
    const UID = 'uid';

    const AGENCY_UID = 'agencyUid';
    const WEB_HOOK_TYPE = 'webHookType';
    const EVENT_TYPE = 'eventType';
    const CALLBACK_URL = 'callbackUrl';
    const OBJECT_UID = 'objectUid';

    const EVENT_TYPE_NEW_INQUIRY = 'NEW_INQUIRY';
    const EVENT_TYPE_NEW_BOOKING = 'NEW_BOOKING';

    const EVENT_TYPE_NEW_PROPERTY = 'NEW_PROPERTY';
    const EVENT_TYPE_UPDATED_PROPERTY = 'UPDATED_PROPERTY';
    const EVENT_TYPE_DELETED_PROPERTY = 'DELETED_PROPERTY';

    const EVENT_TYPE_NEW_BLOCKED_DATES = 'NEW_BLOCKED_DATES';

    const EVENT_TYPE_BOOKING_CANCELLED = 'BOOKING_CANCELLED';
    const EVENT_TYPE_BOOKING_UPDATED = 'BOOKING_UPDATED';

    const EVENT_TYPE_ACTIVATED_PROPERTY = 'ACTIVATED_PROPERTY';
    const EVENT_TYPE_DEACTIVATED_PROPERTY = 'DEACTIVATED_PROPERTY';

    const EVENT_TYPE_PINCODE_CREATED = 'PINCODE_CREATED';
    const EVENT_TYPE_PINCODE_DELETED = 'PINCODE_DELETED';

    const EVENT_TYPE_CHANNEL_ACTIVATED = 'CHANNEL_ACTIVATED';
    const EVENT_TYPE_CHANNEL_DEACTIVATED = 'CHANNEL_DEACTIVATED';

    const EVENT_TYPE_INTEGRATION_ACTIVATED = 'INTEGRATION_ACTIVATED';
    const EVENT_TYPE_INTEGRATION_DEACTIVATED = 'INTEGRATION_DEACTIVATED';

    const WEB_HOOK_TYPE_POST_JSON = 'POST_JSON';
    const WEB_HOOK_TYPE_POST_FORM = 'POST_FORM';
}
