#!/usr/bin/env make

cp: ## Копирование файлов для laradock
	cp ./laravel-horizon/supervisord.d/laravel-horizon.conf.example ./laravel-horizon/supervisord.d/laravel-horizon.conf
	cp ./mysql/docker-entrypoint-initdb.d/createdb.sql.example ./mysql/docker-entrypoint-initdb.d/createdb.sql

---------------: ## ---------------
